### ISSUE TITLE
Gauge charts not updated by real-time update

### ISSUE THREAD

**Issue by ywarnier** [amnuts/opcache-gui#10]
Hi,
Nice little code you have there. Thanks for sharing.

The gauge charts do not seem to be updated by the real-time update. From what I can see, the real-time update really gets a detailed array, but it seems like only the following variables are updated when the AJAX call returns:
* number of cached files
* number of hits
* number of misses
* number of cached keys
* max cached keys
The gauges, the percentage in the middle, the used memory and the free memory do not seem to be updated.
Also, I find it weird that the used memory and free memory are rounded at the nearest MB, when it clearly shows "33.00MB", which suggests the precision is at the percent of MB (i.e. 10KB).

Apart from that, everything seems to be OK :+1:

**Comment by amnuts** [comment]
Thanks for the feedback @ywarnier!  You should find that the last few commits resolve the issues.

**Comment by ywarnier** [comment]
Indeed. Thanks for your little app, it's very nice and handy.
