### ISSUE TITLE
Incorrect directives links to PHP documentation

### ISSUE THREAD

**Issue by krzotr** [amnuts/opcache-gui#103]
The below directives point to an incorrect PHP documentation page
- file_update_protection    
- huge_code_pages           
- jit-max_recursive_returns 
- lockfile_path
- opt_debug_level

In the code you replace `_` with`-`. As you can see, there are 5 exceptions - should stay `_` (underscore).

https://github.com/amnuts/opcache-gui/blob/db9df06889067f99d95bb9f226ec99e663aed196/build/_frontend/interface.jsx#L389

**Comment by amnuts** [comment]
Many thanks for letting me know, @krzotr!  I've applied a fix and released as version 3.5.3.
