### ISSUE TITLE
`interned_strings_buffer` setting doesn't match 'php -i'

### ISSUE THREAD

**Issue by mutoroglin** [amnuts/opcache-gui#111]
Hi everyone,

firstly thanks for this great tool and all the effort you put in!

I would assume that my issue is rather a user problem, I am not yet very experienced with php. But maybe someone has a helpful hint for me....

Because my nextcloud instace complained I intended to increase my `opcache_strings_buffer` and increased the value in my `php.ini` file. After a php restart I confirmed with `sudo -u www-data php -i` that 'opcache_strings_buffer' is set to 64.
However, opcache-gui reports that `opcache_strings_buffer` is still set to 8.

I checked for other configuration files in the subfolder 'conf.d', I tried the `php -i` command with all other users on my server but get always the same setting of 64. Can anyone point me to where my problem is caused?

**Comment by mutoroglin** [comment]
Alright, I ran `phpinfo()` and actually realized that my apache server used a different php.ini file as the system php install.

**Comment by amnuts** [comment]
Glad you got there, @mutoroglin!  Those multiple ini files have definitely caught me out in the past, too.
