### ISSUE TITLE
Update installation instructions in readme file

### ISSUE THREAD

**Issue by luisdev** [amnuts/opcache-gui#115]
When installing opcache-gui on a server, do we ONLY need to copy the /master/index.php file to the server. Or are the associated files also required:

/master/package.json
/master/package-lock.json
/master/composer.json

Do we need to copy all four of those files to the server? Please update the Installing section of the README.md file to explain whether these additional three files are required.
If they are not required, then the README.md should explain what these files are for and why they're included in the package.

**Comment by amnuts** [comment]
Hi @luisdev, thanks for the feedback.

The only file you actually _need_ for the gui is the `index.php` file.  However, it depends on how you want to install the interface and if you want to rebuild it with a different language, or js files, etc.

For example, if simply downloaded the zip file from this repo and wanted to have the gui as-is, I would just copy out the `index.php` file and put it in a place my web server could run it.  

If I want to install it as a dependency in my own project, then I'd add this repo to my project's dependencies in its composer.json file, which would then automatically use this repo's `composer.json` file, and everything would be put in my project's `vendor` directory.

If I wanted to change the language, I'd need to use `package.json` file to install the required js modules (via `npm`) and then I can use the `build/build.php` file to recompile the React components, or change up the language, and so on.  This goes hand-in-hand with the everything else in the `build` directory, as that's where the templates are located.  But if you've no interest at all in doing any of that, you can ignore all those files.

Now, I thought I had detailed all of that in the readme, but it seems maybe not clear enough.  So when I look into another issue that was posted yesterday, I'll also see if there's any way I can make the readme clearer and the intention of the files more visible.

**Comment by luisdev** [comment]
I copied index.php to my Windows Server 2019 (1809) box running IIS 10.0 and PHP 7.4.32. 
Now I just get a blank page when I open https://mysite/index.php in my browser. Is this because of a misconfiguration in opcache-gui? If so, the required configuration steps need to be explained in more detail in the README.me file.

Or does opcache-gui require a specific version of PHP? The README.me file doesn't mention any specific PHP version requirements, so I assume that any version of PHP should be ok. If this is not true, then the PHP version requirements need to be explained in the README.me file.

I have left all the **$options** defaults untouched in index.php.

My phpinfo shows that Zend OPcache Opcode Caching is 'Up and Running'.

**Comment by luisdev** [comment]
UPDATE:
I tried various versions:
- opcache-gui-3.0.0.zip
- opcache-gui-3.3.1.zip and
- opcache-gui-3.4.0.zip

They all give me a blank screen when I run the opcache-gui index.php page.

Then I tried opcache-gui-2.5.4.zip and it worked! So, I'm assuming that the v3 branch of opcache-gui is not compatible with PHP 7. It requires PHP 8, I assume.

**So, the PHP requirements and supported versions  of PHP should be clearly stated in the README.md file of each version of opcache-gui .**

**Comment by amnuts** [comment]
The **second sentence** in the readme states:

> This interface uses ReactJS and Axios and is for modern browsers, and requires a minimum of PHP 7.1.

And the last entire section of the readme is titled:

> Making is compatible with PHP 7.0

Aaaaand, the `composer.json` _also_ has the minimum requirements of:

```json
  "require": {
    "ext-Zend-OPcache": "*",
    "php": ">=7.1.0",
    "ext-json": "*"
  },
```

So, yeah, I think I pretty clearly say what the minimum version of PHP is required and don't need to address that any more in the readme.
