### ISSUE TITLE
When chart is false there are no big numbers

### ISSUE THREAD

**Issue by ryandaniels** [amnuts/opcache-gui#14]
When charts = false, big numbers are not displayed.
Seems like last commit changed the expected behaviour.

Test by changing config from true to false:
'charts'           => false,  // show gauge chart or just big numbers

**Comment by amnuts** [comment]
Thanks for pointing that out.

The numbers were still there but I had adjusted the DOM level so they were no longer styled properly.  Latest revision fixes the problem.
