### ISSUE TITLE
GUI misrepresents zero as "no value"

### ISSUE THREAD

**Issue by ToonSpinISAAC** [amnuts/opcache-gui#16]
Certain OPcache settings, such as `opcache.revalidate_freq`, are integers for which can make sense if they equal zero. However, the OPcache GUI currently shows "no value" instead of "0" if the integer value is zero. This has caused us quite a bit of worry, thinking PHP ini settings weren't getting picked up, before we realized that the problem is in this application.

The problem is a JavaScript comparison that uses `==` instead of `===`. I am making a pull request that fixes this issue.

**Comment by amnuts** [comment]
Thanks very much for the patch! :+1:

**Comment by ToonSpinISAAC** [comment]
No problem, thanks for merging!
