### ISSUE TITLE
Server Software: Wrong value when using PHP-FPM

### ISSUE THREAD

**Issue by cytopia** [amnuts/opcache-gui#18]
I am using Apache (with local PHP installed (PHP 5.4) so that I can use `php_admin_value` inside Apache.

I am also using a remote PHP-FPM server which actually servers the files (PHP 5.6).

On the index page it shows:

| General info |                                                                 |
|-------------|---------------------------------------|
| Zend OPcache   | 7.0.6-dev                                           |
| PHP                     | 5.6.27                                                |
| Host                    | 7d14eb61f4fe                                    |
| Server Software | Apache/2.4.6 (CentOS) PHP/5.4.16 |
| Start time            | 2016-10-16 03:55:05                       |
| Last reset            | never                                                  |

Is this intended?

**Comment by amnuts** [comment]
What details are you expecting to see - which values are wrong?  I can kind of see how the PHP version may by correct if supplied by PHP-FPM and how the SERVER_SOFTWARE value could be correct if being supplied by Apache with 5.4.  It's also possible to change the SERVER_SOFTWARE value (via htaccess, for example).

**Comment by cytopia** [comment]
@amnuts I see. Thanks for the clarification.
