### ISSUE TITLE
APCU

### ISSUE THREAD

**Issue by kbond** [amnuts/opcache-gui#19]
Just found this and I really like it!

Any thoughts on adding APCU functionality? I'm currently using the gui script provided by https://github.com/krakjoe/apcu but it is pretty ugly...

**Comment by amnuts** [comment]
Thanks @kbond :smile: 

I've not thought about adding ACPU functionality at all, to be honest.  I wonder if it would be better to have a separate script for ACPU and Opcache, or if people would prefer them in the one file?

**Comment by futureweb** [comment]
for me APCu functionality would better fit into a seperate Script ... :-)

**Comment by dugwood** [comment]
APCu already has a GUI: https://github.com/krakjoe/apcu/blob/master/apc.php
Which is fine too :-)
