### ISSUE TITLE
Add a Test if opcache extension is working

### ISSUE THREAD

**Issue by bbalet** [amnuts/opcache-gui#20]
Hi,

You test if the extension is loaded, but you don't test if it is working or not. If the extension is not working, the functions opcache_get_status() and opcache_get_configuration() would return FALSE. This causes an error in compileState function when you try to merge the various status arrays (they would be boolean values instead of arrays).

**Comment by amnuts** [comment]
Thanks for the feedback.  There's now a check in place for installed opcache but not turned on.
