### ISSUE TITLE
offline installation not possible

### ISSUE THREAD

**Issue by arashdalir** [amnuts/opcache-gui#28]
Hi,
before anything else, thanks for the great tool! it has helped me a lot already.
the problem is, I have to use this tool on a machine which has no internet access, most of the features seem to fail as they are dependent on JS code loaded from //cdn.jsdelivr.net/; which of course, is not available. I intend to resolve the issue by downloading the resources and rewriting this part of the code, but it would be great if this problem would be resolved in the main repository too. but maybe you don't see it that way, which would also be fine! :)

Thanks again

Best Wishes

**Comment by amnuts** [comment]
Thanks, @arashdalir, I'm glad it's been useful.

In essence it's just a few lines you have to update once you pull down the javascript and save it locally.  I had to do this for my role once as a firewall stopped external access to the js.  I appreciate that maybe it's not ideal, but I would prefer to keep the files distributed to a minimum.  At the moment, for example, people only need one file to get up and running and that makes it much easier for the majority of installs.

If other people considered this an issue then I might look into doing something, but as it stands I'm pretty much going to leave it up to the individual to point to their own local copies of the js libraries, where ever they may be on their file system.

**Comment by arashdalir** [comment]
Hi @amnuts,

I appreciate your answer. as said, it was just a suggestion and I did exactly as you said (saving them locally), just wanted to provide some feedback, which is only possible as an "issue". Thanks again for the great tool :)

**Comment by amnuts** [comment]
@arashdalir all feedback is much appreciated, thanks! :)
