### ISSUE TITLE
More of a question then an issue

### ISSUE THREAD

**Issue by SWS-Denzle** [amnuts/opcache-gui#32]
Hi, thanks for your tool!

Not sure if this is the correct place to ask but I can't find a comments section.

The start time you have listed there, what does this actually mean?
Every page refresh I do, the start time changes, shouldn't this stay the same?

Sorry if it sounds a noobish question but Google doesn't really have the answer and its not only your tool that does this. 

Thanks again.

**Comment by amnuts** [comment]
Hi @SWS-Denzle 

The start time is when the server was started as reported by the `opcache_get_status` function.  It shouldn't update every refresh if you have a long running server like apache.  For example, I just checked a server now and the start date was '2017-08-18 09:28:12' and the last reset time was '2017-10-19 12:33:42'.  Perhaps you're using fpm and it handles that differently?  Or maybe there's something a little dodgy with your opcache?

Andy

**Comment by SWS-Denzle** [comment]
Hi @amnuts 

I thought so, thank you for confirming this. 
It didn't make sense that this would change this often.

I sent over your reply to the hosting company that I opened up a ticket with about this and here is the response:

For the notes from your developer, we are no using fpm, but from what I can see on some topics around stackoverflow the fact that we are using mod_cgi instead of mod_php may result in differences between the two, if your old server is running mod_php for example, the opcache service however is running as expected on our servers.

This is alittle be beyond my knowledge at this stage, does this mean more to you?

I see lots of good things about OPCache and I really think that we're not getting any of the benifits from it due to misconfiguration.

Thanks

**Comment by theycallmepepper** [comment]
@SWS-Denzle  Would it be possible for you to post a screenshot of the output to get a better understanding of the rest of your settings? (Making sure to blur any sensitive paths,etc)

**Comment by infosws** [comment]
Hi @theycallmepepper,

Hopefully this shows below, I am trying to get access to adjust variables. Just tested a completely new box and out of all the hosting setups I have played with, I have one that finally works!

![image](https://user-images.githubusercontent.com/26347831/36347106-de98c98e-1446-11e8-817f-52cc9416c092.png)
