### ISSUE TITLE
invalidate by path

### ISSUE THREAD

**Issue by visages** [amnuts/opcache-gui#34]
Hi,

thanks a lot for this amazing tool, which I'm using on 2 servers.

I don't see how I could invalidate files by path rather than individually, E.G. invalidating all files below /var/www/foo/bar/

For instance when I commit some files, or worse a Drupal security update with a bunch of files, on various sites,  it's a pain to invalidate each file separately  ...

Thank you.

PS : Resetting whole cache is a huge performance hit, so I'd prefer to use a more progressive solution.

**Comment by amnuts** [comment]
There is no invalidation by path, only individual files or the whole thing.  Sounds like an idea, though, so I'll have a look into it.

**Comment by visages** [comment]
Great, that would be awesome ! Looking forward to hearing good news. Thanks a lot.

**Comment by amnuts** [comment]
To be quite honest, I totally forgot about this request - sorry!

In the `v3` branch currently being worked on you'll be able to invalidate any files that match the search in one go.
