### ISSUE TITLE
Fatal error: Namespace declaration 

### ISSUE THREAD

**Issue by Niresh12495** [amnuts/opcache-gui#35]
> 
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /public_html/op.php on line 3

**Comment by amnuts** [comment]
Sorry for the slowness in responding; the index.php file does have the namespace declaration as the first statement after the opening php tag:

```
<?php

namespace OpcacheGui;
```

Could you perhaps be using an older version of the file, or maybe you have something else in your file that's not present in the one from the repo?
