### ISSUE TITLE
array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by df1paw** [amnuts/opcache-gui#37]
Hi.

I currently experience the following error:
Warning: array_merge(): Argument #1 is not an array in /homepages/[....]/opcache.php on line 198

And no data is shown on the dashboard

Any ideas?

Kind regards,
    Andreas

**Comment by amnuts** [comment]
Hi; what version are you using?

**Comment by ArturNadolski** [comment]
Same error at my site. `$status['memory_usage']` and `$status['opcache_statistics']` are NULL.

**Comment by amnuts** [comment]
Thanks for the detailed feedback! This script should handle these kinds of issues without throwing errors, so I'll look into it soon.

**Comment by df1paw** [comment]
Hi.
I'm using the latest version from here. 
I just changed opcache.file_cache_only=1; to =0 in my  php.ini -> seems to work now ;-)

Regards,
    Andreas

**Comment by ArturNadolski** [comment]
Just checked what df1paw found and I can confirm it. It's working when "file cache only" option is disabled.
So this is only workaround not final solution.

**Comment by amnuts** [comment]
Unfortunately, the `opcache_get_statistics` returns very, _very_ little information when the `file_cache_only` setting it `1`, which leaves the gui basically just displaying the opcache settings and the links to the functions.  If this ever changes then I'll update the code, but there's little I can do with this right now other than making it not break if you have the setting to `1`.

Sorry it took a while!
