### ISSUE TITLE
updates for new variables

### ISSUE THREAD

**Issue by chrcoluk** [amnuts/opcache-gui#38]
I know is a minor thing but if possible please provide an update for missing variables such as "opcache.file_update_protection" thanks.

**Comment by amnuts** [comment]
I've been a bit remiss recently in making any changes to the script.  I'll try to carve out some time soon so that I can update it to include the missing variables and tidy up other issues that have been opened.

**Comment by amnuts** [comment]
Sorry this took a while!

As it turns out, the `opcache_get_configuration` function doesn't return four of the particular values, so I've compensated for that in other ways and you will now see all the settings.

**Comment by amnuts** [comment]
Although the opcache-gui compensates for missing attributes, the PHP source has been fixed as of https://github.com/php/php-src/commit/768ad70f70a1bebed38e2b06a7515e3c61482f75
