### ISSUE TITLE
keys chart

### ISSUE THREAD

**Issue by slavkoja** [amnuts/opcache-gui#39]
Please, can you add chart of keys usage?

**Comment by amnuts** [comment]
How's you mean @slavkoja?  What info is it you're wanting to see?

**Comment by slavkoja** [comment]
Hi, i mean percentage from ``num_cached_keys`` and ``'max_cached_keys``. I see them in statistics as exact numbers, but percentage will allow quick inspection.

**Comment by amnuts** [comment]
Hopefully the version I just tagged with v2.5.0 will be what you're looking for. :)
