### ISSUE TITLE
2.0.1 release

### ISSUE THREAD

**Issue by jkrehm** [amnuts/opcache-gui#4]
Would you consider doing a 2.0.1 release (git tag) so the most recent changes will be available via Composer without having to use "dev-master" as the dependency?

**Comment by amnuts** [comment]
Yeah, no problem!

https://github.com/amnuts/opcache-gui/releases/tag/v2.0.1

**Comment by jkrehm** [comment]
Fantastic. Thanks for the quick response and great tool!

**Comment by amnuts** [comment]
Thanks, I appreciate it!
