### ISSUE TITLE
memory_consumption not in MB

### ISSUE THREAD

**Issue by Steve8291** [amnuts/opcache-gui#40]
Great script!
I would like to suggest one change:
Under the 
> Directives: memory consumption

This is not reporting in MB as I would expect.
I have 128MB as the value in my php.ini settings and it is reporting 134217728 which is the value in bytes. It would make more sense to have it display in MB since that is how it is entered with `opcache.memory_consumption=128`

**Comment by amnuts** [comment]
Thanks!

That's now been fixed.
