### ISSUE TITLE
The script not show any data 

### ISSUE THREAD

**Issue by vandark25** [amnuts/opcache-gui#42]
The script does not show any data.
If it detects Opcache because if I reset it the counter is set to 0
but the web doesn't show anything.

Plesk Onyx + Ubuntu 18 + Apache + FPM + Opcache
![opcache](https://user-images.githubusercontent.com/40995825/63752089-e8614980-c8b0-11e9-8f47-e55a2a88d4e0.JPG)
![opcache running](https://user-images.githubusercontent.com/40995825/63752939-6a05a700-c8b2-11e9-88e5-a26d55e9a94e.JPG)

**Comment by jp-onsite** [comment]
opcache_get_status is in plesk in standard settings disabled. Go to your Domain specific PHP Settings and delete the value for "disable_functions"
