### ISSUE TITLE
Not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by CreativeNative** [amnuts/opcache-gui#46]
After updating to composer version ^1.10.1 I get the following error message and autoloading isn't working anymore. Could you please have a look.

> Deprecation Notice: Class OpcacheGui\OpCacheService located in ./vendor/amnuts/opcache-gui/index.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by akalongman** [comment]
+1

**Comment by amnuts** [comment]
I've tidied this up in the `v3` branch - plus I've changed the namespace of the class.

I haven't completed all the work I want to do on it yet, but it's a better split if you just want to use the class or want to compile to a single `index.php` file (by using `composer build`).

If you want to check it out and see if works for you, please feel free and drop any feedback.  Just remember that it's not quite complete yet.
