### ISSUE TITLE
Excessive load time, file usage tab

### ISSUE THREAD

**Issue by 7starsone** [amnuts/opcache-gui#53]
Hello,
when cache is empty or you have a few files the script is fast but if you have something like eg.
_used memory: 676.69MB
number of cached files: 65,856_

it takes too much to load the page, even 2 minutes or more
I didn't take a look at the code but in my opinion the issue is the number of files because you don't paginate and you load all the cached files references at once. `File usage` tab? So, it's really slow to invalidate a file in this situation. Can you fix it, please?

Thanks

**Comment by 7starsone** [comment]
To make it perfect:
1) load all the references into an array (fast)
2) let the user choose how many elements of that array in one page (or at least, find a compromise testing for speed, eg. 50 elements on a page? No elements on the pages at all (by user option, maybe) and just use the fast filter? That's it...really fast this way.
Hope this helps

**Comment by amnuts** [comment]
Thanks for reporting.

Sounds like a sensible idea to me so I'll look into making those changes in the near future.

**Comment by 7starsone** [comment]
I would be grateful if you wrote here after the change, in order to be notified
Thanks 👍 😄

**Comment by amnuts** [comment]
@7starsone , I'm working on a new branch which moves all the frontend to be in React and has pagination for the files.  I've tried it out with 65K files and it worked quite nicely.  The branch isn't quite ready to move into master yet - I've a few more tidy-ups and docs to finish up, but feel free to check it out and see if it'll work out for you.

**Comment by amnuts** [comment]
@7starsone, I've now merged into master and released version 3.0.0 which includes the pagination functionality.
