### ISSUE TITLE
3.0.1 still reports itself as 3.0.0

### ISSUE THREAD

**Issue by tjharman** [amnuts/opcache-gui#58]
Very minor, but be nice to correct so people aren't confused about the version they're running.

Thanks for this gui, it's very lovely.

**Comment by amnuts** [comment]
🤦 

I forgot to update the version numbers!  That'll teach me for throwing out a quick update!

Thanks for pointing it out @tjharman.  I've updated on master but am reluctant to delete the tag and have a do-over, or force push now that it's been published.  So it's just in master for now and I'll do better when making the next update that I release (properly!)

**Comment by tjharman** [comment]
All good, just thought I'd point it out.
