### ISSUE TITLE
[new PHP user] file location for index.php for OpCache?

### ISSUE THREAD

**Issue by StefanScott** [amnuts/opcache-gui#6]
Hi -

I'm new to PHP (have mostly used Java previously) and I would like to use opcache-gui to monitor a PrestaShop ecommerce app which I'm running using PHP 5.6.7 with nginx + php-fpm on Debian.

The nginx server is serving the PrestaShop app from the following folder (which already contains its own `index.php` file):
```
/var/www/shop1.mysite.com/public_html/prestashop
```
So my question is: **Where should I place the `index.php` file for opcache-gui?**

Should I simply create another nginx server and put the `index.php` file for opcache-gui in that server's top-level public folder?

If so, will opcache-gui also "see" what's happening on the other server (the main one, serving my PrestaShop app)?

Thanks for any help!

**Comment by amnuts** [comment]
Hi, 

No need to create another server - just rename the index.php file from opcache-gui to anything else, something like opcache.php for example, just anything that doesn't conflict with files already there because of the shop app.

Andy
