### ISSUE TITLE
OPCache GUI does not load in Moodle's Behat environment

### ISSUE THREAD

**Issue by abias** [amnuts/opcache-gui#61]
Hi Andrew,

as you know, we have packaged your great OPCache GUI into a Moodle plugin on https://github.com/moodleuulm/moodle-tool_opcache.

Today, I had to see that, while the plugin works perfectly in my browsers, OPCache GUI is not working anymore in Moodle's Behat environment.

When I watch the Behat tests, the step where the test goes to the Moodle OPCache settings page fails as the OPCache GUI does not load there:
<img width="1080" alt="grafik" src="https://user-images.githubusercontent.com/1092118/100337572-d4d2f000-2fd7-11eb-970f-986fe5f71734.png">

The same happens when I take over manual command over the testing browser and open the OPCache GUI file directly without the Moodle wrapper:
<img width="1079" alt="grafik" src="https://user-images.githubusercontent.com/1092118/100337755-15326e00-2fd8-11eb-86a1-b96a57849673.png">

Clicking on the error message in the web inspector console, I get this line:
<img width="1077" alt="grafik" src="https://user-images.githubusercontent.com/1092118/100337833-27aca780-2fd8-11eb-8ab6-31aaa46f7ad5.png">

It might be important to say that the testing browser is a really old Firefox 47, but there are reasons for the Moodle developers to use this old browser:
<img width="583" alt="grafik" src="https://user-images.githubusercontent.com/1092118/100337984-53c82880-2fd8-11eb-9a51-b0fcf76556ee.png">

Do you have any idea what could cause OPCache not to load in this environment, Andrew?

If you need any more details from me, please let me know.

Cheers,
Alex

**Comment by amnuts** [comment]
Hi @abias,

Not sure off the top of my head, but if I were to guess it's because the javascript used in the interface uses ES6 constructs and the build process doesn't do any work to make that js backwards compatible.  So it's likely there's something there that's incompatible.

Might be handy to see what the code looks like on the lines specific; 117 and 458 by the looks of the screenshots.

Andy

**Comment by abias** [comment]
Hi @amnuts ,

thank you for this feedback!

Your explanation makes sense to me. According to https://caniuse.com/es6, Firefox does not fully support ES6 until version 54.

This problem arose just recently when I switched my Behat testing environment from Chrome (which I have been running up to then) to Firefox (which is Moodle's default for Behat testing). Switching back to Chrome, the Behat tests work again.

I think I will leave it then with Chrome and can close this issue.

Thanks,
Alex
