### ISSUE TITLE
Use minified production versions of React?

### ISSUE THREAD

**Issue by abias** [amnuts/opcache-gui#63]
Hi @amnuts ,

I saw on https://github.com/amnuts/opcache-gui/blob/master/index.php#L393-L394 that you are using the development libraries of React even in your built release.

Is there any reason for this or would you want to change that to the minified production versions?

Cheers,
Alex

**Comment by amnuts** [comment]
Hi @abias,

No reason other than an oversight on my part.  I had the development files included whilst I was doing the redevelopment of the interface and forgot to change them to the minified versions.

Good spot! I'll get that changed shortly.

Cheers!

**Comment by amnuts** [comment]
@abias, release 3.2.0 now uses the minified React libraries as we as ensuring they will always be the most recent versions available.
