### ISSUE TITLE
Can invalidate files even if disabled with variable

### ISSUE THREAD

**Issue by FabioPedretti** [amnuts/opcache-gui#69]
I set allow_invalidate to false in the options, and indeed I no longer can invalidate specific files.
However, when I enter some filter in the search, I get the "Invalidate all matching files" link.

**Comment by amnuts** [comment]
Nice catch @FabioPedretti - I'll get that fixed soon.

The backend will (should) actually prevent the reset from being performed, but you definitely shouldn't see the option if it's turned off!
