### ISSUE TITLE
jit expansion

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [amnuts/opcache-gui#79]
There are a few macros for opcache.git:
- disable: Completely disabled, cannot be enabled at runtime. Equals to 0.
- off: Disabled, but can be enabled at runtime. Equals to 0
- tracing/on: Use tracing JIT. Enabled by default and recommended for most users: Equals to 1254
- function: Use function JIT. Equals to 1205

Would be nice if opcache-gui could expand any of these values showing also is description. For instance tracing will be:
- 1: Enable use of AVX, if the CPU supports it (CPU-specific optimization)
- 2: Perform global register allocation (Register allocation)
- 5: Use tracing JIT. Profile on the fly and compile traces for hot code segments (Trigger)
- 4: Use call graph

**Comment by MichaIng** [comment]
The GUI shows the related directives, of course when these are available at all (i.e. PHP8.0 running):
![jit](https://user-images.githubusercontent.com/28480705/147953025-ef38ac11-2456-494d-b553-e2382923862a.png)

Or do you mean to have a description of what e.g. `tracing` means directly in the GUI? I think the added maintenance for this is not worth the outcome, given that you can simply click the directive to get to the official PHP docs which explains everything precisely: https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.jit

**Comment by javiergutierrezchamorro** [comment]
Thanks. Yes, I was refering to the second point, and understand your thought. Even so, their equivalents could change from one PHP version to another.

**Comment by MichaIng** [comment]
I wonder whether there are PHP-versioned docs available, cannot find it currently, but I think I remember seeing a page with a banner at the top that it's not the latest PHP version 🤔. However, if behaviour of a directive changes, there is usually a note in the `Changelog` column of the config list and sometimes also further notes in the dedicated directive section.

**Comment by amnuts** [comment]
I think that if it's just a description of the advanced usage for the `opcache.jit`, ie, if someone has used a numeric value rather than `tracing`, `off`, etc., then I'm OK with adding it.  I would have a similar maintenance overhead with the optimization levels which are fairly hardcoded from the PHP source, so see no real difference with the CRTO values.  I think I would just leave `tracing`, etc., if someone has put in those values and not try to convert them to the more expanded equivalent, though.

**Comment by amnuts** [comment]
😂 Well, it seems I'm ahead of myself as I already have the jit expansion in there and just forgot about it 😆 

![image](https://user-images.githubusercontent.com/684421/148649034-7c1c146a-ca21-4bf2-85be-89c41dfffc70.png)

**Comment by MichaIng** [comment]
Ah nice. Then I guess showing the same when the shortcuts are used wouldn't be much overhead? But I agree, if one does not touch the setting or uses a shortcut, then the explanation of the effective optimisation levels is probably not required, and that the settings key is a link to related docs is sufficient.

**Comment by amnuts** [comment]
The confusion was my reasoning for not expanding the `tracing`, etc.  If someone manually put in the value into their ini file and then in the gui it showed a lot more and nothing what they entered, then I can imagine it being odd and them wondering what was wrong with the gui. 😉

**Comment by amnuts** [comment]
But in saying that, I could always show the value and then expand upon it underneath - best of both worlds 😁

**Comment by amnuts** [comment]
This is what it now does:

![image](https://user-images.githubusercontent.com/684421/148651296-c631afea-e1af-45a0-a396-425b66b27e0c.png)

![image](https://user-images.githubusercontent.com/684421/148651310-25a07a2c-fedb-4582-924e-0fb15dfcb39f.png)

![image](https://user-images.githubusercontent.com/684421/148651326-a575f262-062f-43b7-a025-ca2e75a23904.png)

will push a branch and do merges in a bit.

**Comment by MichaIng** [comment]
Little suggestion: Probably it is possible to visually separate the applied value and the description of the optimisation levels a bit? Also for consistency the applied numerical value could then also be shown.

**Comment by amnuts** [comment]
I'll give it a whirl with the spacing.  The way it renders the directive values is pretty fixed, but I'll have a swing at it.

And yeah, that's a good point about the numeric value being shown - will add that. 👍

**Comment by amnuts** [comment]
Ah, yeah, this is a little more consistent now and with some spacing...

![image](https://user-images.githubusercontent.com/684421/148655373-f8b68419-135b-492e-bfde-3e5815b99006.png)

![image](https://user-images.githubusercontent.com/684421/148655385-d02ae065-91f6-47bc-9236-5d68a2779720.png)

**Comment by amnuts** [comment]
Fixed with the release of 3.3.1
