### ISSUE TITLE
Information when a file has been cached or modified in the cache

### ISSUE THREAD

**Issue by je-mos** [amnuts/opcache-gui#82]
Hello,

first of all thank you very much for your tool. This is really useful!

I'd like to ask if it would be possible to add a timestamp to every file in the cached file list with the information when the file has been cached or modified in the cache (because the file on disk changed). As far as I know, currently only the last use time is displayed in the GUI file list.

If I remember right, the time of adding the file to the cache should be available via opcache_get_status(). The returned file list should include a key "timestamp" which contains the UNIX timestamp when that file was added to the cache.

Could this information be added to opcache-gui?

Thank you very much!

Best regards,
je-mos

**Comment by amnuts** [comment]
Hi @je-mos,

Thanks for the kind words, and really sorry for the delay in getting back to you!  Yes, I don't see why that can't happen as the information is there anyway. 😄  I'm a bit busy for a week or two, but I'll see about adding it in soon.

**Comment by amnuts** [comment]
Just to let you know (in case you want to try it before it gets merged into master), this is currently in the branch `working/3.4.0`, but not going to be too long until I merge it into master.

**Comment by je-mos** [comment]
Hi @amnuts,

thanks a lot! I'm pleased to hear that you've already found the time to work on this. Really nice!

I think I'll wait until the new feature is officially released. I'm very busy at the moment, but will definitely check it out soon.

Keep up the good work!

Best regards,
je-mos

**Comment by amnuts** [comment]
Now merged into master
