### ISSUE TITLE
strict MIME type errors, page does not load on certain sites

### ISSUE THREAD

**Issue by crankedguy** [amnuts/opcache-gui#98]
Hi,

I cannot get this to run on one site of mine, while it runs fine on others. I rebuilt it with local .js files because of data protection measures in the country. As said it works fine on e.g. a WP site.
Here on this site I get
`opcm.php:1 Refused to execute script from 'https://domain.com/opcm/react.production.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
I get this for all 3 .js scripts

Basically in the inspector I get
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>OPcache statistics on domain.com</title>
        <script src="react.production.min.js"></script>
        <script src="react-dom.production.min.js"></script>
        <script src="axios.min.js"></script>
```
with a red cross on the first line saying this is a html document and so throwing the MIME errors.

I also did the following 
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>OPcache statistics on domain.com</title>
        <script type="text/javascript" src="react.production.min.js"></script>
        <script type="text/javascript" src="react-dom.production.min.js"></script>
        <script type="text/javascript" src="axios.min.js"></script>
```
but it leads to the same result

Any idea what to do or how to change the code here?

**Comment by crankedguy** [comment]
Well, when it comes to such situations I usually freak out completely as I don't know what;'s going on : 
Just to try it out I completely inlined the code in the head section on the page where it not worked. After that it was working without any issues. Guess what. Without doing anything on the other side I called it there, where it was not inlined, and suddenly I got the same MIME issues and it was not working on this page anymore.
Did not get it back to work until I inlined the code there, too.
I hate "magical" things on my own server, as I was sure it something to do with .htaccess from the page where it was not working. But that can;t be the case anymore because why is it not working on the page it worked before.

Whatever... for future releases : Would it be too hard for you to inline the code when automatically when building with -j?

**Comment by amnuts** [comment]
Interesting... On the face of it, I would say that your web server (apache, nginx, or whatever you use) was not handling the files correctly and attributing the wrong MIME type - and, yeah, that could come as a result of the .htaccess file, I guess.  Having the contents inlined meant there were no additional files for your web server to handle, so it was all down to the browser to render, which it could do.

It's not a bad idea to have the content all inlined, tbh.  It does mean it sticks more to the "only need a single file to run" mentality I've been trying to retain, so I'll probably look into making that change at some point - thanks for the suggestion!

**Comment by amnuts** [comment]
@crankedguy, I've made that change to the `develop` branch if you want to try it out?

If you use `-j` for local js, it'll embed the javascript into the `index.php` file.

There's also an additional `-r` (or `--remote-js`) option where you can specify where you get the 3rd-party libraries from, `cloudflare`, `jsdelivr`, or `unpkg`.  And that'll be used for the `<script>` links or where the js is downloaded from if using `-j`.

**Comment by amnuts** [comment]
Have now merged this into the `master` branch, so I'm going to consider this issue closed.  But if you have any problems with it, just let me know.

**Comment by crankedguy** [comment]
Yea will do, sorry got sucked up the last few days. And thanks for implementing this.

**Comment by amnuts** [comment]
No need to apologise, @crankedguy! 😃  I figured it was a small enough set of changes that it was pretty safe to put out and seemed fine when I tested (famous last words right there!)
